{"time":"2024-11-24T10:43:24.8980295+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-24T10:43:24.8980295+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\Jiang241023\\wandb\\run-20241124_104324-ruklzx4z\\logs\\debug-core.log"}
{"time":"2024-11-24T10:43:25.0247918+01:00","level":"INFO","msg":"created new stream","id":"ruklzx4z"}
{"time":"2024-11-24T10:43:25.0247918+01:00","level":"INFO","msg":"stream: started","id":"ruklzx4z"}
{"time":"2024-11-24T10:43:25.0247918+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"ruklzx4z"}}
{"time":"2024-11-24T10:43:25.0247918+01:00","level":"INFO","msg":"sender: started","stream_id":"ruklzx4z"}
{"time":"2024-11-24T10:43:25.0247918+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"ruklzx4z"}}
{"time":"2024-11-24T10:43:25.3077599+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-24T11:00:55.3117479+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 9356"}
{"time":"2024-11-24T17:27:51.5367349+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"time":"2024-11-24T17:27:53.8803743+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-26T03:30:39.9763151+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-27T07:57:35.5222617+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"time":"2024-11-27T07:57:37.9551357+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:19.5450874+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:21.6643089+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T17:10:26.1951761+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-11-27T19:27:55.3583435+01:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream"}
{"time":"2024-11-27T19:29:15.3544951+01:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream"}
{"time":"2024-11-28T19:45:39.9865645+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-28T20:45:39.976751+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-29T09:45:38.1813161+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ruklzx4z/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
