{"time":"2024-11-27T19:38:01.955741+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-27T19:38:01.955741+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\Jiang241023\\wandb\\run-20241127_193801-ce0yjhp4\\logs\\debug-core.log"}
{"time":"2024-11-27T19:38:02.082108+01:00","level":"INFO","msg":"created new stream","id":"ce0yjhp4"}
{"time":"2024-11-27T19:38:02.0826274+01:00","level":"INFO","msg":"stream: started","id":"ce0yjhp4"}
{"time":"2024-11-27T19:38:02.0826274+01:00","level":"INFO","msg":"sender: started","stream_id":"ce0yjhp4"}
{"time":"2024-11-27T19:38:02.0826796+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"ce0yjhp4"}}
{"time":"2024-11-27T19:38:02.0826274+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"ce0yjhp4"}}
{"time":"2024-11-27T19:38:02.36562+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-27T19:38:42.3808674+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 42224"}
{"time":"2024-11-28T05:45:37.6368782+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/ce0yjhp4/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
